services:
  api:
    build: .
    container_name: api-notificacoes
    restart: always
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      - nginx-network

  nginx:
    image: nginx:alpine
    container_name: api-notificacoes-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true